### ISSUE TITLE
Wrong property visiblity in Widget classes

### ISSUE THREAD

**Issue by thomasrawiel** [schams-net/t3extensions_widget#3]
In the class **AbstractListExtensionsWidget** the properties 
- $configuration
- $view
- $options
are declared as `private` properties.

Since they are accessed in the classes **LastNewExtensionsWidget** and **LastUpdatedExtensionsWidget**, which are descendants of  **AbstractListExtensionsWidget**, they should be declared as `protected`.

**Comment by schams-net** [comment]
Thanks for reporting the issue. The visibility of the properties are fixed in [release v1.1.2](https://github.com/schams-net/t3extensions_widget/releases/tag/v1.1.2). New version uploaded to the [TYPO3 Extension Repository](https://extensions.typo3.org), and also available on [Packagist](https://packagist.org/packages/schams-net/t3extensions-widget).
